package xgc

type WCHAR uint16
type WORD uint16
type DWORD uint32
type BYTE byte
type SHORT int16

const (
	XINPUT_GAMEPAD_LEFT_THUMB_DEADZONE  = 7849
	XINPUT_GAMEPAD_RIGHT_THUMB_DEADZONE = 8689
	XINPUT_GAMEPAD_TRIGGER_THRESHOLD    = 30
)

const (
	XINPUT_GAMEPAD_DPAD_UP        = 0x0001
	XINPUT_GAMEPAD_DPAD_DOWN      = 0x0002
	XINPUT_GAMEPAD_DPAD_LEFT      = 0x0004
	XINPUT_GAMEPAD_DPAD_RIGHT     = 0x0008
	XINPUT_GAMEPAD_START          = 0x0010
	XINPUT_GAMEPAD_BACK           = 0x0020
	XINPUT_GAMEPAD_LEFT_THUMB     = 0x0040
	XINPUT_GAMEPAD_RIGHT_THUMB    = 0x0080
	XINPUT_GAMEPAD_LEFT_SHOULDER  = 0x0100
	XINPUT_GAMEPAD_RIGHT_SHOULDER = 0x0200
	XINPUT_GAMEPAD_A              = 0x1000
	XINPUT_GAMEPAD_B              = 0x2000
	XINPUT_GAMEPAD_X              = 0x4000
	XINPUT_GAMEPAD_Y              = 0x8000
)

// -+-CAPABILITIES
//  |-----GAMEPAD
//  |-----VIBRATION
//  +-KEYSTROKE
//  +-STATE
//  |-----GAMEPAD

type XINPUT_CAPABILITIES struct {
	Type      BYTE
	SubType   BYTE
	Flags     WORD
	Gamepad   XINPUT_GAMEPAD
	Vibration XINPUT_VIBRATION
}

type XINPUT_GAMEPAD struct {
	Buttons      WORD
	LeftTrigger  BYTE  // 0~255
	RightTrigger BYTE  // 0~255
	ThumbLX      SHORT // -32768~32767
	ThumbLY      SHORT // -32768~32767
	ThumbRX      SHORT // -32768~32767
	ThumbRY      SHORT // -32768~32767
}

type XINPUT_KEYSTROKE struct {
	VirtualKey WORD
	Unicode    WCHAR
	Flags      WORD
	UserIndex  BYTE
	HidCode    BYTE
}

type XINPUT_STATE struct {
	PacketNumber DWORD
	Gamepad      XINPUT_GAMEPAD
}

type XINPUT_VIBRATION struct {
	LeftMotorSpeed  WORD // 0~65535
	RightMotorSpeed WORD // 0~65535
}
